### ISSUE TITLE
Wear OS by Google Support

### ISSUE THREAD

**Issue by EvilInsultGenerator** [EvilInsultGenerator/android-app#10]
It would be nice if the Evil Insult Generator could work on smartwatches too. 😈

**Comment by Biren-Nayak** [comment]
@EvilInsultGenerator Can i work on this issue?

**Comment by EvilInsultGenerator** [comment]
> 
> 
> @EvilInsultGenerator Can i work on this issue?

That would be awesome! Thank you so much!
