### ISSUE TITLE
Modularize Android Wear OS App

### ISSUE THREAD

**Issue by EvilInsultGenerator** [EvilInsultGenerator/android-app#135]
![WearOS](https://github.com/EvilInsultGenerator/android-app/assets/19539741/8b9d0ab6-7e07-4eec-a639-3ea60a72fd98)

It would be good to modularize the Wear OS app and update GitHub Actions so that it creates two .apk files (one .apk for mobile devices like phones and tablets PLUS one .apk for smartwatches).

**Comment by EvilInsultGenerator** [comment]
Are you up for this, @Biren-Nayak?

**Comment by Biren-Nayak** [comment]
@EvilInsultGenerator My PC not working currently, so won't be able to, will reply if any update.

**Comment by EvilInsultGenerator** [comment]
> @EvilInsultGenerator My PC not working currently, so won't be able to, will reply if any update.

Thanks.

**Comment by Jenish-1235** [comment]
Hello there, I would like to work on this issue. Could you please assign this issue to me

**Comment by EvilInsultGenerator** [comment]
> Hello there, I would like to work on this issue. Could you please assign this issue to me

Awesome. Let me know if you have any questions.
