### ISSUE TITLE
Chinese not supported?

### ISSUE THREAD

**Issue by brijagstu7** [EvilInsultGenerator/android-app#143]
Changing language to chinese gives me '***'s

**Comment by EvilInsultGenerator** [comment]
> Changing language to chinese gives me '***'s

We do not have Chinese insults in the database yet unfortunately.
Please send me an [email](mailto:marvin@evilinsult.com?Subject=Evil%20Insult%20Generator%20Proposal&Body=Hej%20fuckers%2C%0A%0Aplease%20add%20this%20beauty%3A%0A%0Ainsult%3A%20...%0Alanguage%3A%20...%0Acomment%20%28optional%29%3A%20...%0A%0A...%0A) with your favorite Chinese insults and I will add them.
Feel welcome to put several in one email. I need the insult itself and maybe a comment which explains more complex insults.
Thanks! 👍

**Comment by EvilInsultGenerator** [comment]
Checking and adding translation on [Crowdin](https://crowdin.com/project/evil-insult-generator-android) would be awesome too. 😅
