### ISSUE TITLE
Homescreen Widget

### ISSUE THREAD

**Issue by EvilInsultGenerator** [EvilInsultGenerator/android-app#160]
What do you think about a homescreen widget that shows a new insult hourly?

Example:
![photo_2024-02-12_22-22-51](https://github.com/EvilInsultGenerator/android-app/assets/19539741/f23ec41a-0683-4e2f-a5d4-0cc5a2601a82)

**Comment by Jenish-1235** [comment]
Hello there, I would like to contribute to this issue during hacktoberfest '24. I am pretty sure, I can create this widget feature. Could you let me know whether this issue is still pending and accepting PRs or not?

**Comment by EvilInsultGenerator** [comment]
> Hello there, I would like to contribute to this issue during hacktoberfest '24. I am pretty sure, I can create this widget feature. Could you let me know whether this issue is still pending and accepting PRs or not?

Thank you so much for your offer to help.
It would be awesome if you could implement a widget.

**Comment by Jenish-1235** [comment]
Surely, I would love to contribute

**Comment by EvilInsultGenerator** [comment]
Are you working on this, @Jenish-1235?
(Don't stress, I'm just curious.)

**Comment by Jenish-1235** [comment]
Yes , I am working on this. It's just I am little busy with my office work.
