### ISSUE TITLE
Can't scroll to up on Large system font size

### ISSUE THREAD

**Issue by htethy** [EvilInsultGenerator/android-app#182]
System font size on my phone

![Screenshot_20240904-141408_Settings](https://github.com/user-attachments/assets/ed643f11-0797-45e2-9d3e-07c13d67854e)

## Screen Recording
https://github.com/user-attachments/assets/5e5c2d68-502a-45ea-8fca-c0272599480c

## Tech info
- Device: Samsung A125F
- OS: Android 12 OneUI 4.1
- App Version: 4.3

**Comment by EvilInsultGenerator** [comment]
Thanks for reporting this.
Anyone interested in fixing this please let us know.

**Comment by rubenquadros** [comment]
Removing the `layout_gravity` from the `FameLayout` which is the first child of `ScrollView` does the trick for me. Shall I submit an MR?

**Comment by EvilInsultGenerator** [comment]
> Removing the `layout_gravity` from the `FameLayout` which is the first child of `ScrollView` does the trick for me. Shall I submit an MR?

Awesome, thanks for your help. Please open a PR. 👍

@jahirfiquitiva, do you see any problems in that approach?

**Comment by rubenquadros** [comment]
We have to do it programmatically though. If the content is not scrollable we would still want to center the `FameLayout`. Please do share your thoughts on the solution!
