### ISSUE TITLE
Cannot find a browser

### ISSUE THREAD

**Issue by Alex-Esko** [EvilInsultGenerator/android-app#31]
Everything works fine, except:

Clicking on the three dots in the upper rigth corner reveals the buttons: Twitter, website, suggestion, support, legal.
None of them works, it only says "Cannot find a browser".

System: Android 11 on S10 with latest updates. Language German.

**Comment by EvilInsultGenerator** [comment]
Which browsers do you have installed? Which one is your default?

May you share a .gif of the problem?

I just tested on Android 10 and it works. Do you have an idea, @jahirfiquitiva?

**Comment by Alex-Esko** [comment]
Besides Chrome also Firefox Browser, which i made the default.
Restoring Chrome as default, but not uninstalling Firefox, did not change the behaviour.

Video is here:
https://user-images.githubusercontent.com/5099066/110249000-1a5a6e00-7f74-11eb-8a4f-c0515c48edf8.mp4

**Comment by Cwpute** [comment]
same problem here, my browser is FOSS Browser, available on f-droid:https://f-droid.org/en/packages/de.baumann.browser/

**Comment by Cwpute** [comment]
same problem here, my browser is FOSS Browser, available on f-droid: https://f-droid.org/en/packages/de.baumann.browser/

**Comment by Cwpute** [comment]
same problem here, my browser is FOSS Browser, available on f-droid: https://f-droid.org/en/packages/de.baumann.browser/

**Comment by Cwpute** [comment]
same problem here, my browser is FOSS Browser, available on f-droid: https://f-droid.org/en/packages/de.baumann.browser/

**Comment by Cwpute** [comment]
same problem here, my browser is FOSS Browser, available on f-droid: https://f-droid.org/en/packages/de.baumann.browser/

**Comment by Cwpute** [comment]
same problem here, my browser is FOSS Browser, available on f-droid: https://f-droid.org/en/packages/de.baumann.browser/

**Comment by Cwpute** [comment]
same problem here, my browser is FOSS Browser, available on f-droid: https://f-droid.org/en/packages/de.baumann.browser/

**Comment by EvilInsultGenerator** [comment]
I just got hands on an Android 11 smartphone myself and can verify this behaviour. 
@jahirfiquitiva, can we somehow help you with fixing this?
