### ISSUE TITLE
Modify description to specify that the app can't do anything

### ISSUE THREAD

**Issue by licaon-kter** [EvilInsultGenerator/android-app#33]
...unless it can connect to those 2 websites.

**Comment by licaon-kter** [comment]
Ref: https://gitlab.com/fdroid/fdroiddata/-/commit/4c9d9887bdaddc49cb7469ca7921dc4b91eda833

**Comment by EvilInsultGenerator** [comment]
Hey, the app needs access to a backend to get the insults. 
To be sure, you are speaking about `evilinsult.com/api` and `slave.evilinsult.com/api`, aren't you?

The backend itself is open source and I upload database dumps from time to time too. That is the reason why the app did not get the `NonFreeNet` antifeature originally. There is no interface in the app itself but the user can change the string in the source. 
I personally have no real problem with the antifeature though. If you like, you can add it.

**Comment by licaon-kter** [comment]
Already added the AntiFeature, but I'd like to have the description clearer.

**Comment by EvilInsultGenerator** [comment]
> Alreadya added, but I'd like to have the description clearer.

What do you mean by that?

**Comment by licaon-kter** [comment]
I mean, the description talks about the app, the app and the app.

It's not clear that the app does not do anything without an Internet connection.

**Comment by EvilInsultGenerator** [comment]
> 
> 
> I mean, the description talks about the app, the app and the app.
> 
> It's not clear that the app does not do anything without an Internet connection.

Oh, I see. You are right with that.

**Comment by EvilInsultGenerator** [comment]
I will close this for now as it seems answered but feel welcome to re-open with more questions.
I love F-Droid. Thank you so much for your support! 😘
