### ISSUE TITLE
Migrate From Travis To GitHub Actions

### ISSUE THREAD

**Issue by EvilInsultGenerator** [EvilInsultGenerator/android-app#44]
**Pros**:

- GitHub Actions is better integrated into GitHub
- GitHub Actions is easier to configure and maintain
- We love to stick deep inside GitHub's ass

**Comment by DipayanP007** [comment]
Hey @EvilInsultGenerator can you assign me this? I would like to work on this?

**Comment by EvilInsultGenerator** [comment]
> Hey @EvilInsultGenerator can you assign me this? I would like to work on this?

Sure 👍

**Comment by EvilInsultGenerator** [comment]
Travis has those features at the moment:

- Upload signed .apk to a release on GitHub
- Upload signed .apk to a Telegram channel
- Upload signed .apk to a Slack channel

That is fine for me but you might suggest other options. I don't think that an automatic upload to Google Play is necessary as there are not so many releases.

**Comment by EvilInsultGenerator** [comment]
Maybe a Codecov integration would be nice to have.

**Comment by EvilInsultGenerator** [comment]
@DipayanP007, are you still working on it?

**Comment by EvilInsultGenerator** [comment]
I will ask Jahir to work on this.

**Comment by EvilInsultGenerator** [comment]
Done with `v3.9 `🥳
