### ISSUE TITLE
Update View Binding

### ISSUE THREAD

**Issue by EvilInsultGenerator** [EvilInsultGenerator/android-app#45]
The 'kotlin-android-extensions' Gradle plugin is deprecated. Please use this migration guide (https://goo.gle/kotlin-android-extensions-deprecation) to start working with View Binding (https://developer.android.com/topic/libraries/view-binding) and the 'kotlin-parcelize' plugin.

**Comment by devrahul-2508** [comment]
I would like to work on this issue

**Comment by EvilInsultGenerator** [comment]
> I would like to work on this issue

That would be great! 👍

**Comment by EvilInsultGenerator** [comment]
Are you able to do it this month, @devrahul-2508?

**Comment by EvilInsultGenerator** [comment]
I will ask Jahir to work on this.

**Comment by EvilInsultGenerator** [comment]
Done with `v3.9 `🥳
