### ISSUE TITLE
Support Themed Icons on Android 13+

### ISSUE THREAD

**Issue by EvilInsultGenerator** [EvilInsultGenerator/android-app#88]
Android 13 introduces [Themed App Icons](https://developer.android.com/about/versions/13/features#themed-app-icons). It would be nice to support them.

**Comment by Shanta-11** [comment]
Can I work on this?

**Comment by EvilInsultGenerator** [comment]
> Can I work on this?

That would be great. 👍

I don't have a monochrome icon yet so you need to design it first.

**Comment by Shanta-11** [comment]
> > Can I work on this?
> 
> That would be great. 👍
> 
> I don't have a monochrome icon yet so you need to design it first.

I'll give some iterations, you can decide amongst them

**Comment by EvilInsultGenerator** [comment]
> > > Can I work on this?
> > 
> > 
> > That would be great. 👍
> > I don't have a monochrome icon yet so you need to design it first.
> 
> I'll give some iterations, you can decide amongst them

Hey @Shanta-11,
did you come up with something?
If not, I would do it myself next week. 😅

**Comment by Shanta-11** [comment]
Hey, i didn't do it, 🤧

**Comment by EvilInsultGenerator** [comment]
I just added the [monochrome icon](https://www.figma.com/file/AxMjPG9SEaNLH3NK1Xt1SC/Evil-Insult-Generator?node-id=1797%3A13042&t=7PJgM0Sjd1jhhVk6-1).
May you please check if I implemented it correctly, @Shanta-11?

**Comment by Shanta-11** [comment]
> I just added the [monochrome icon](https://www.figma.com/file/AxMjPG9SEaNLH3NK1Xt1SC/Evil-Insult-Generator?node-id=1797%3A13042&t=7PJgM0Sjd1jhhVk6-1). May you please check if I implemented it correctly, @Shanta-11?

Yeah, i think that'll work

**Comment by EvilInsultGenerator** [comment]
> > I just added the [monochrome icon](https://www.figma.com/file/AxMjPG9SEaNLH3NK1Xt1SC/Evil-Insult-Generator?node-id=1797%3A13042&t=7PJgM0Sjd1jhhVk6-1). May you please check if I implemented it correctly, @Shanta-11?
> 
> Yeah, i think that'll work

Thanks for checking. 👍

**Comment by sebastien46** [comment]
Sorry for necro'ing this issue. I see the file in the source, but no in-app option to enable it, nor is it enabled by default.

**Comment by EvilInsultGenerator** [comment]
> Sorry for necro'ing this issue. I see the file in the source, but no in-app option to enable it, nor is it enabled by default.

It's done in the device settings. Maybe [this guide](https://www.androidpolice.com/android-13-themed-icons-how-to-activate/) helps you.
